pipeline {
    agent ('master')
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
//            agent {
//                docker {
//                    image 'qnib/pytest'
//                }
//            }
//          steps {
//                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
          steps {
		sh """
		   PYTHONPATH=''
		   nosetests --with-xunit --all-modules --traverse-namespace --with-coverage --cover-inclusive sources/test_calc.py
		   python -m coverage xml --include=*
		   pylint -f parseable -d I0011,R0801 sources/ | tee pylint.out
		   """

            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}
